<a href="https://colab.research.google.com/github/LailaBulh/Procesamiento_Lenguaje_Natural/blob/main/Clasificacion_texto_LB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Clasificación de texto**

**Nombre:** Laila Montserrat Bulhosen Ramos **Matrícula**: 263166

**Docente:** Dr. Rogelio Florencia Juarez

**Materia:** Procesamiento de Lenguaje Natural



**Link Github:** [Clasificación_texto_LB](https://github.com/LailaBulh/Procesamiento_Lenguaje_Natural/blob/main/Clasificacion_texto_LB.ipynb)

**Fecha:** Mayor 2026

## **1. Carga de conjunto de datos**

In [1]:
### Drive connection

from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd

In [3]:
text_original = pd.read_csv('/content/drive/MyDrive/Procesamiento Lenguaje Natural/IMDB Reviews.csv')

In [4]:
display(text_original.head())

print('\nTotal de filas en el documentos:' ,text_original['review'].count())

print('\nTotal de valores nulos encontrados:\n', text_original.isnull().sum())

                                              review  sentimento
0  One of the other reviewers has mentioned that ...           1
1  A wonderful little production. <br /><br />The...           1
2  I thought this was a wonderful way to spend ti...           1
3  Basically there's a family where a little boy ...           0
4  Petter Mattei's "Love in the Time of Money" is...           1

Total de filas en el documentos: 50000

Total de valores nulos encontrados:
 review        0
sentimento    0
dtype: int64

## **2. Preprocesamiento de datos**

In [5]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

In [6]:
nltk.download('stopwords')

english_stopwords = set(stopwords.words("english"))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [31]:
### Convertir a minúsculas

text_min = text_original['review'].str.lower()

text_min.head()

0    one of the other reviewers has mentioned that ...
1    a wonderful little production. <br /><br />the...
2    i thought this was a wonderful way to spend ti...
3    basically there's a family where a little boy ...
4    petter mattei's "love in the time of money" is...
Name: review, dtype: object

In [32]:
### Eliminar puntuaciones

text_punct = text_min.str.replace(r'<br />', '', regex=False)

text_punct.head()

0    one of the other reviewers has mentioned that ...
1    a wonderful little production. the filming tec...
2    i thought this was a wonderful way to spend ti...
3    basically there's a family where a little boy ...
4    petter mattei's "love in the time of money" is...
Name: review, dtype: object

In [13]:
### Definir stop_words y port_stem
### Se utiliza english_stopwords ya que el texto esta en inglés

stop_words = english_stopwords
port_stem = PorterStemmer()

def clean_text(text):
  ### Eliminar httml
  text = re.sub(r'<br />', '', text)

  # Eliminar caracteres que no sean letras
  text = re.sub('[^a-zA-Z]', ' ', text)

  # Convertir a minúsculas
  text = text.lower()

  # Tokenizar por espacios en blanco
  tokens = text.split()

  # Stemming y eliminación de stopwords
  tokens = [port_stem.stem(word) for word in tokens if word not in stop_words]

  # Reconstruir el texto limpio
  cleaned_text = ' '.join(tokens)

  return cleaned_text

In [14]:
# Aplicar la función a la columna 'review'

text_original['review_cleaned'] = text_original['review'].apply(clean_text)

display(text_original.head())

                                              review  sentimento  \
0  One of the other reviewers has mentioned that ...           1
1  A wonderful little production. <br /><br />The...           1
2  I thought this was a wonderful way to spend ti...           1
3  Basically there's a family where a little boy ...           0
4  Petter Mattei's "Love in the Time of Money" is...           1

                                      review_cleaned
0  one review mention watch oz episod hook right ...
1  wonder littl product film techniqu unassum old...
2  thought wonder way spend time hot summer weeke...
3  basic famili littl boy jake think zombi closet...
4  petter mattei love time money visual stun film...

## **3. EDA**

In [58]:
from nltk import word_tokenize

In [59]:
### EDA

all_tokens_cleaned = word_tokenize( " ".join(df_new['review']), language='english')

KeyError: 'review'