<a href="https://colab.research.google.com/github/LailaBulh/Procesamiento_Lenguaje_Natural/blob/main/Clasificacion_texto_LB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Clasificación de texto**

**Nombre:** Laila Montserrat Bulhosen Ramos **Matrícula**: 263166

**Docente:** Dr. Rogelio Florencia Juarez

**Materia:** Procesamiento de Lenguaje Natural



**Link Github:** [Clasificación_texto_LB](https://github.com/LailaBulh/Procesamiento_Lenguaje_Natural/blob/main/Clasificacion_texto_LB.ipynb)

**Fecha:** Mayor 2026

## **1. Carga de conjunto de datos**

In [26]:
### Drive connection

from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [27]:
import pandas as pd

In [28]:
text_original = pd.read_csv('/content/drive/MyDrive/Procesamiento Lenguaje Natural/IMDB Reviews.csv')

In [29]:
display(text_original.head())

print('\nTotal de filas en el documentos:' ,text_original['review'].count())

print('\nTotal de valores nulos encontrados:\n', text_original.isnull().sum())

                                              review  sentimento
0  One of the other reviewers has mentioned that ...           1
1  A wonderful little production. <br /><br />The...           1
2  I thought this was a wonderful way to spend ti...           1
3  Basically there's a family where a little boy ...           0
4  Petter Mattei's "Love in the Time of Money" is...           1

Total de filas en el documentos: 50000

Total de valores nulos encontrados:
 review        0
sentimento    0
dtype: int64

## **2. Preprocesamiento de datos**

In [30]:
import re

In [31]:
### Convertir a minúsculas

text_min = text_original['review'].str.lower()

text_min.head()

0    one of the other reviewers has mentioned that ...
1    a wonderful little production. <br /><br />the...
2    i thought this was a wonderful way to spend ti...
3    basically there's a family where a little boy ...
4    petter mattei's "love in the time of money" is...
Name: review, dtype: object

In [32]:
### Eliminar puntuaciones

text_punct = text_min.str.replace(r'<br />', '', regex=False)

text_punct.head()

0    one of the other reviewers has mentioned that ...
1    a wonderful little production. the filming tec...
2    i thought this was a wonderful way to spend ti...
3    basically there's a family where a little boy ...
4    petter mattei's "love in the time of money" is...
Name: review, dtype: object

In [33]:
def clean_text(text):
  text = re.sub